enquisas/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    # path('lista_enquisas/', views.lista_enquisas, name='lista_enquisas'),
    path('<int:id_enquisa>/', views.detalle_enquisa, name='detalle_enquisa'),
    path('crear_enquisa/', views.crear_enquisa, name='crear_enquisa'),
    path('crear_opcion/', views.crear_opcion, name='crear_opcion'),
]

proxecto_DAW/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('enquisas/', include('enquisas.urls')),
    path('usuarios/', include('django.contrib.auth.urls')),
    path('usuarios/', include('usuarios.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login_user/', views.login_user, name='login'),
    path('logout_user/', views.logout_user, name='logout'),
    path('register_user/', views.register_user, name='register_user'),
]

enquisas/models.py
from django.db import models
import datetime as dt
from django.contrib.auth.models import User

class Enquisa(models.Model):
    pregunta = models.CharField(max_length=200)
    data_creacion = models.DateTimeField(default=dt.datetime.now())
    dias_activo = models.IntegerField(default=3)
    usuarios_que_votaron = models.ManyToManyField(User)
    imaxe = models.ImageField(null=True, blank=True, upload_to='images/')

    def __str__(self):
        return f'{self.id} - {self.pregunta}'
    
class Opcion(models.Model):
    texto_opcion = models.CharField(max_length=100)
    enquisa = models.ForeignKey(Enquisa, on_delete=models.CASCADE)
    votos = models.IntegerField(default=0)

    def __str__(self) -> str:
        return f'{self.enquisa.pregunta} - {self.texto_opcion}'

usuarios/models.py
from django.db import models

# Create your models here.

enquisas/forms.py
from django import forms
from django.forms import ModelForm

from .models import Enquisa, Opcion

class FormularioEnquisa(ModelForm):

    pregunta = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    dias_activo = forms.IntegerField(widget=forms.NumberInput(attrs={'class':'form-control'}))

    class Meta:
        model = Enquisa
        fields = ('pregunta', 'dias_activo', 'imaxe')
        

class FormularioOpcion(ModelForm):
    enquisa = forms.ModelChoiceField(Enquisa.objects.all(), widget=forms.Select(attrs={'class':'form-control'}))
    texto_opcion = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))

    class Meta:
        model = Opcion
        fields = ('enquisa', 'texto_opcion' )

usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class RegisterUserForm(UserCreationForm):
    first_name = forms.CharField(label='Nome')
    last_name = forms.CharField(label='Apelido')
    email = forms.EmailField()
    is_staff = forms.BooleanField()
    
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', 'is_staff')

    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            if field != 'is_staff':
                self.fields[field].widget.attrs.update({'class':'form-control'})


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Nome de usuario', widget=forms.TextInput(attrs={'class':'form-control'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class':'form-control'}))

enquisas/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Enquisa, Opcion
from .forms import FormularioEnquisa, FormularioOpcion
from django.contrib import messages
from django.contrib.auth.decorators import login_required 

def home(request):
    context = {
        'lista_enquisas': Enquisa.objects.all()
    }

    return render(request, 'enquisas/lista_enquisas.html', context)


@login_required(login_url="/usuarios/login_user/")
def detalle_enquisa(request, id_enquisa):

    if request.method == 'POST':

        id_opcion = int(request.POST['opciones'])

        user = request.user
        opcion = Opcion.objects.get(pk=id_opcion)

        if user in opcion.enquisa.usuarios_que_votaron.all():
            messages.success(request, message='Síntoo, xa votaches nesta enquisa, non podes volver a votar.',
                             extra_tags='danger')
            return redirect('detalle_enquisa', opcion.enquisa.id)
        else:

            opcion.enquisa.usuarios_que_votaron.add(user)

            opcion.votos += 1
            opcion.save()

            context = {
                'opcion': opcion
            }
            
            return render(request,'enquisas/votar_opcion.html', context)
    
    else:

        context = {
            'enquisa': Enquisa.objects.get(pk=id_enquisa)
        }
        return render(request, 'enquisas/detalle_enquisa.html', context)


@login_required(login_url="/usuarios/login_user/")
def crear_enquisa(request):

    if request.method == 'POST': 
        form = FormularioEnquisa(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            messages.success(request, 'A enquisa creouse correctamente.', extra_tags='success')
            messages.success(request, 'Introduza outra enquisa.', extra_tags='info')
            return render(request, 'enquisas/nova_enquisa.html', {'form': FormularioEnquisa()})
        
    else:
        form = FormularioEnquisa()
        return render(request, 'enquisas/nova_enquisa.html', {'form': form})

@login_required(login_url="/usuarios/login_user/")
def crear_opcion(request):

    if request.method == 'POST': 
        form = FormularioOpcion(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, 'A opción creouse correctamente.', extra_tags='success')
            messages.success(request, 'Introduza outra opción.', extra_tags='info')
            return render(request, 'enquisas/nova_opcion.html', {'form': FormularioOpcion()})
        
    else:
        form = FormularioOpcion()
        return render(request, 'enquisas/nova_opcion.html', {'form': form})

usuarios/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from .forms import RegisterUserForm, LoginUserForm


def login_user(request):
     
    if request.method == 'POST':

        form = LoginUserForm(request, request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, f'Benvido {username}', extra_tags='success')
                next = request.GET.get('next', 'home')
                return redirect(next)
        
    else:
        if 'next' in request.GET:
            messages.success(request, 'Por favor, inicia sesión antes de acceder a esa páxina.', extra_tags='danger')

        form = LoginUserForm()

    context = {'form': form}
    return render(request, 'usuarios/login.html', context)


def logout_user(request):

    logout(request)
    messages.success(request, 'Acabas de sair do sistema.', extra_tags='success')
    return redirect('home')


def register_user(request):
     
    if request.method == 'POST':

        form = RegisterUserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(request, username=username, password=password)
            login(request, user)
            messages.success(request, f'Benvido {username}', extra_tags='success')
            
            return redirect('home')
        
    else:

        form = RegisterUserForm()

    context = {'form': form}
    return render(request, 'usuarios/register_user.html', context)

enquisas/templates/enquisas/base_template.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Enquisas</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'enquisas/assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'enquisas/css/styles.css' %}" rel="stylesheet" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    </head>
    <body>
        <!-- Navigation-->
        {% include 'enquisas/navigation_bar.html' %}
        <!-- Header-->
        {% block header %}

        {% endblock %}


        <!-- Section-->
        {% block section %}

        {% endblock %}
        
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'enquisas/js/scripts.js' %}"></script>
    </body>
</html>

enquisas/templates/enquisas/detalle_enquisa.html
{% extends 'enquisas/base_template.html' %}

{% block section %}

<!-- Product section-->
<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">

        {% include 'enquisas/messages.html' %}

        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6">

                {% if enquisa.imaxe %}
                    <img class="card-img-top mb-5 mb-md-0" src="{{ enquisa.imaxe.url }}" alt="..." />
                {% else %}
                    <img class="card-img-top mb-5 mb-md-0" src="https://dummyimage.com/600x700/dee2e6/6c757d.jpg" alt="..." />
                {% endif %}
                
            </div>
            <div class="col-md-6">
                <div class="small mb-1"> Detalle da pregunta con id {{ enquisa.id }} </div>
                <h1 class="display-5 fw-bolder"> {{ enquisa.pregunta }} </h1>
                <p class="lead">
                    <form action="{% url 'detalle_enquisa' enquisa.id %}" method="post">

                        {% csrf_token %}
                        {% for opcion in enquisa.opcion_set.all %}
                            <input id = "{{ opcion.id }}" type="radio" name="opciones" value="{{ opcion.id }}">
                            <label for="{{ opcion.id }}"> {{ opcion.texto_opcion }} - ({{opcion.votos}} votos) </label><br/>
                        {% endfor %}
                        <br><br>

                        <button type="submit" class="btn btn-secondary" 
                        {% if user in enquisa.usuarios_que_votaron.all %}
                             disabled 
                        {% endif %}
                         >Votar por esta opción</button>
                        
                    </form>
                    
                </p>
            </div>
        </div>
    </div>
</section>

{% endblock %}

enquisas/templates/enquisas/header.html
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Ti pregunta ben</h1>
            <p class="lead fw-normal text-white-50 mb-0">Que eu xa verei se che contesto</p>
        </div>
    </div>
</header>

enquisas/templates/enquisas/lista_enquisas.html
{% extends 'enquisas/base_template.html' %}

{% block header %}

    {% include 'enquisas/header.html' %}

{% endblock %}

{% block section %}

    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">

            {% include 'enquisas/messages.html' %}

            <br/>
            <br/>

            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

                {% for enquisa in lista_enquisas %}

                <div class="col mb-5">
                    <div class="card h-100">
                        <!-- Sale badge-->
                        <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
                        <!-- Product image-->
                        {% if enquisa.imaxe %}
                            <img class="card-img-top" src="{{ enquisa.imaxe.url }}" alt="..." />
                        {% else %}
                            <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                        {% endif %}
                        <!-- Product details-->
                        <div class="card-body p-4">
                            <div class="text-center">
                                <!-- Product name-->
                                <h5 class="fw-bolder">{{ enquisa.pregunta }}</h5>
                                <!-- Product reviews-->
                                <div class="d-flex justify-content-center small text-warning mb-2">
                                    <div class="bi-star-fill"></div>
                                    <div class="bi-star-fill"></div>
                                    <div class="bi-star-fill"></div>
                                    <div class="bi-star-fill"></div>
                                    <div class="bi-star-fill"></div>
                                </div>
                                {{ enquisa.opcion_set.all | length }} opcións
                            </div>
                        </div>
                        <!-- Product actions-->
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'detalle_enquisa' enquisa.id %}">Ver enquisa</a></div>
                        </div>
                    </div>
                </div>

                {% endfor %}

            </div>
        </div>
    </section>

{% endblock %}

enquisas/templates/enquisas/messages.html
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{message.extra_tags}} animate__animated animate__fadeOut animate__delay-5s " role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}

enquisas/templates/enquisas/navigation_bar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{% url 'home' %}">Enquisas varias</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'home' %}">Inicio</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Novo</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if user.is_authenticated %}
                            <li><a class="dropdown-item" href="{% url 'crear_enquisa'%}">Nova enquisa</a></li>
                            <li><a class="dropdown-item" href="{% url 'crear_opcion'%}"> Nova opcion </a></li>
                        {% else %}
                            <li><a class="dropdown-item disabled" href="{% url 'crear_enquisa'%}">Nova enquisa</a></li>
                            <li><a class="dropdown-item disabled" href="{% url 'crear_opcion'%}"> Nova opcion </a></li>
                        {% endif %}

                    </ul>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'register_user' %}">Rexístrate</a></li>
                {% endif %}
                
            </ul>
        </div>
    </div>
</nav>

enquisas/templates/enquisas/nova_enquisa.html
{% extends 'enquisas/base_template.html' %}

{% block section %}

<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">

        {% include 'enquisas/messages.html' %}

        <form action="{% url 'crear_enquisa' %}" method="post" enctype="multipart/form-data">

            {% csrf_token %}
            
            {{ form }}
            
            <br/><br/>

            <button type="submit" class="btn btn-secondary">Crear nova enquisa</button>
        </form>

    </div>
</section>

{% endblock %}

enquisas/templates/enquisas/nova_opcion.html
{% extends 'enquisas/base_template.html' %}

{% block section %}

<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">

        {% include 'enquisas/messages.html' %}

        <form action="{% url 'crear_opcion' %}" method="post">

            {% csrf_token %}
            
            {{ form }}
            
            <br/><br/>

            <button type="submit" class="btn btn-secondary">Crear nova opción</button>

        </form>
    </div>
</section>

{% endblock %}

enquisas/templates/enquisas/votar_opcion.html
{% extends 'enquisas/base_template.html' %}

{% block section %}

<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">

        {% include 'enquisas/messages.html' %}

        <h2> Acabas de votar pola opción </h2>
        
        <h1>{{opcion.id}}-{{opcion.texto_opcion}}</h1>

        <h2> da enquisa {{opcion.enquisa.pregunta}}</h2>

        <h3>Esta opción agora ten {{ opcion.votos }} votos</h3>

        <a href="{% url 'detalle_enquisa' opcion.enquisa.id %}">Ver resultados da enquisa {{opcion.enquisa.id}}</a>

    </div>
</section>  

{% endblock %}

usuarios/templates/usuarios/login.html
{% extends 'enquisas/base_template.html' %}

{% block section %}

<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">

        {% include 'enquisas/messages.html' %}

        <form action="" method="post">
            {% csrf_token %}
            
            {{ form.as_p }}
            <br/>


            <input type="submit" class="btn btn-primary" value="login">
        </form>
    </div>
</section>

{% endblock %}

usuarios/templates/usuarios/register_user.html
{% extends 'enquisas/base_template.html' %}

{% block section %}

<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">

        {% comment %} {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{message.extra_tags}} animate__animated animate__fadeOut animate__delay-5s " role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %} {% endcomment %}

        {% if form.errors %}
            <div class="alert alert-danger animate__animated animate__fadeOut animate__delay-5s " role="alert">
                Houbo un problema co seu rexistro. Por favor, corrixa os erros e inténteo de novo.
            </div>
        {% endif %}

        <form action="" method="post">
            {% csrf_token %}

            {{ form.as_p }}

            <br/>
            <br/>

            <input type="submit" class="btn btn-primary" value="rexistrarse">
        </form>
    </div>
</section>

{% endblock %}